/********************************************************************************
** Form generated from reading UI file 'runstatehelppage.ui'
**
** Created: Fri May 15 15:16:54 2020
**      by: Qt User Interface Compiler version 4.6.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_RUNSTATEHELPPAGE_H
#define UI_RUNSTATEHELPPAGE_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_RunstateHelpPage
{
public:
    QLabel *label_22;
    QLabel *labelSignalSystem;
    QLabel *labelSignalSystem_2;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_56;
    QLabel *label_57;
    QLabel *label_58;
    QLabel *label_59;
    QLabel *label_60;
    QLabel *label_61;
    QLabel *label_63;
    QLabel *label_64;
    QLabel *label_65;
    QLabel *label_62;
    QLabel *label_66;
    QLabel *label_67;
    QLabel *label_68;
    QLabel *label_70;
    QLabel *labelSignalSystem_4;
    QLabel *label_72;
    QLabel *label_74;
    QLabel *label_75;
    QLabel *label_76;
    QLabel *label_77;
    QLabel *label_78;
    QLabel *label_79;
    QLabel *label_3;
    QLabel *label_80;
    QLabel *label_81;
    QLabel *label_82;
    QLabel *label_83;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *labelSignalSystem_8;
    QLabel *labelSignalSystem_9;
    QLabel *labelSignalSystem_10;
    QLabel *labelSignalSystem_11;
    QLabel *label_89;
    QLabel *label_90;
    QLabel *label_91;
    QLabel *label_92;
    QLabel *label_93;
    QLabel *label_94;
    QLabel *labelSignalSystem_12;
    QLabel *labelSignalSystem_13;
    QLabel *labelSignalSystem_14;
    QLabel *labelSignalSystem_15;
    QLabel *labelSignalSystem_16;
    QLabel *labelSignalSystem_17;
    QLabel *labelSignalSystem_18;
    QLabel *labelSignalSystem_19;
    QLabel *labelSignalSystem_20;
    QLabel *labelSignalSystem_21;
    QLabel *labelSignalSystem_22;
    QLabel *labelSignalSystem_23;
    QLabel *labelSignalSystem_24;
    QLabel *labelSignalSystem_25;
    QLabel *labelSignalSystem_26;
    QLabel *label_95;
    QLabel *labelBattery;
    QLabel *labelBatteryP;
    QLabel *label_14;
    QLabel *labelBatteryN;
    QLabel *label_13;
    QLabel *labelBatteryTemperature;
    QLabel *labelBatteryTemperature_2;
    QLabel *labelRP;
    QLabel *labelSignalSystem_7;
    QLabel *labelSignalSystem_27;
    QLabel *labelSignalSystem_28;
    QLabel *labelSignalSystem_29;
    QLabel *labelSignalSystem_30;
    QLabel *labelSignalSystem_31;
    QLabel *labelSignalSystem_32;
    QLabel *labelSignalSystem_33;
    QLabel *labelSignalSystem_34;
    QLabel *labelSignalSystem_35;
    QLabel *labelSignalSystem_36;
    QLabel *labelSignalSystem_37;
    QLabel *labelSignalSystem_38;
    QLabel *labelSignalSystem_39;
    QLabel *labelSignalSystem_40;
    QLabel *labelSignalSystem_41;
    QLabel *labelSignalSystem_42;
    QLabel *labelSignalSystem_43;
    QLabel *label_97;
    QLabel *label_98;
    QLabel *labelSignalSystem_44;
    QLabel *labelSignalSystem_45;
    QLabel *label_71;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_69;
    QLabel *label_73;
    QLabel *labelSignalSystem_46;
    QLabel *labelSignalSystem_47;
    QLabel *labelSignalSystem_48;
    QLabel *labelSignalSystem_49;
    QLabel *labelSignalSystem_50;
    QLabel *labelSignalSystem_51;
    QLabel *labelSignalSystem_52;
    QLabel *label_84;
    QLabel *label_85;
    QLabel *labelSignalSystem_5;
    QLabel *label_86;
    QLabel *labelSignalSystem_53;

    void setupUi(QWidget *RunstateHelpPage)
    {
        if (RunstateHelpPage->objectName().isEmpty())
            RunstateHelpPage->setObjectName(QString::fromUtf8("RunstateHelpPage"));
        RunstateHelpPage->resize(800, 450);
        RunstateHelpPage->setStyleSheet(QString::fromUtf8("QWidget\n"
"{\n"
"	background-color: rgb(51,153,255);\n"
"}\n"
"\n"
"QLabel\n"
"{\n"
" color:white;\n"
"font:20px, \"SimHei\";\n"
"\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"border-image: url(:/image/buttonUP.jpg);\n"
"font:20px, \"SimHei\";\n"
"color:rgb(0, 32, 96);\n"
"border-radius:2px;\n"
"outline:none;\n"
"}\n"
""));
        label_22 = new QLabel(RunstateHelpPage);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(282, 153, 141, 91));
        label_22->setStyleSheet(QString::fromUtf8("border:2px solid white;"));
        label_22->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        labelSignalSystem = new QLabel(RunstateHelpPage);
        labelSignalSystem->setObjectName(QString::fromUtf8("labelSignalSystem"));
        labelSignalSystem->setGeometry(QRect(360, 220, 15, 15));
        labelSignalSystem->setStyleSheet(QString::fromUtf8("border-radius:7px;\n"
"background-color:red;\n"
""));
        labelSignalSystem_2 = new QLabel(RunstateHelpPage);
        labelSignalSystem_2->setObjectName(QString::fromUtf8("labelSignalSystem_2"));
        labelSignalSystem_2->setGeometry(QRect(360, 192, 15, 15));
        labelSignalSystem_2->setStyleSheet(QString::fromUtf8("border-radius:7px;\n"
"background-color:rgb(0,255,0);\n"
""));
        label_23 = new QLabel(RunstateHelpPage);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(300, 183, 51, 30));
        label_24 = new QLabel(RunstateHelpPage);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(300, 218, 51, 21));
        label_25 = new QLabel(RunstateHelpPage);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(2, 2, 141, 271));
        label_25->setStyleSheet(QString::fromUtf8("border:2px solid white;"));
        label_25->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        label_26 = new QLabel(RunstateHelpPage);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(10, 30, 51, 30));
        label_27 = new QLabel(RunstateHelpPage);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(10, 60, 71, 30));
        label_28 = new QLabel(RunstateHelpPage);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(10, 90, 51, 30));
        label_29 = new QLabel(RunstateHelpPage);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(10, 120, 71, 30));
        label_30 = new QLabel(RunstateHelpPage);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(10, 150, 71, 30));
        label_31 = new QLabel(RunstateHelpPage);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(10, 180, 71, 30));
        label_32 = new QLabel(RunstateHelpPage);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(10, 210, 71, 30));
        label_33 = new QLabel(RunstateHelpPage);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(142, 2, 141, 301));
        label_33->setStyleSheet(QString::fromUtf8("border:2px solid white;"));
        label_33->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        label_34 = new QLabel(RunstateHelpPage);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(150, 30, 51, 30));
        label_35 = new QLabel(RunstateHelpPage);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(150, 60, 61, 30));
        label_36 = new QLabel(RunstateHelpPage);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(150, 90, 51, 30));
        label_37 = new QLabel(RunstateHelpPage);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(150, 120, 81, 30));
        label_38 = new QLabel(RunstateHelpPage);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(150, 150, 61, 30));
        label_39 = new QLabel(RunstateHelpPage);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(150, 180, 51, 30));
        label_40 = new QLabel(RunstateHelpPage);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(150, 210, 51, 30));
        label_41 = new QLabel(RunstateHelpPage);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(150, 240, 81, 30));
        label_42 = new QLabel(RunstateHelpPage);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(282, 2, 141, 151));
        label_42->setStyleSheet(QString::fromUtf8("border:2px solid white;"));
        label_42->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        label_43 = new QLabel(RunstateHelpPage);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(290, 30, 51, 30));
        label_44 = new QLabel(RunstateHelpPage);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(290, 60, 51, 30));
        label_45 = new QLabel(RunstateHelpPage);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(290, 90, 51, 30));
        label_46 = new QLabel(RunstateHelpPage);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(422, 2, 141, 268));
        label_46->setStyleSheet(QString::fromUtf8("border:2px solid white;"));
        label_46->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        label_47 = new QLabel(RunstateHelpPage);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(430, 30, 51, 30));
        label_48 = new QLabel(RunstateHelpPage);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(430, 60, 71, 30));
        label_52 = new QLabel(RunstateHelpPage);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(150, 270, 51, 30));
        label_53 = new QLabel(RunstateHelpPage);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(10, 240, 41, 30));
        label_54 = new QLabel(RunstateHelpPage);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(422, 269, 141, 180));
        label_54->setStyleSheet(QString::fromUtf8("border:2px solid white;"));
        label_54->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        label_55 = new QLabel(RunstateHelpPage);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(430, 298, 51, 30));
        label_56 = new QLabel(RunstateHelpPage);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(430, 330, 51, 30));
        label_57 = new QLabel(RunstateHelpPage);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(430, 390, 51, 30));
        label_58 = new QLabel(RunstateHelpPage);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(430, 360, 51, 30));
        label_59 = new QLabel(RunstateHelpPage);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(430, 417, 51, 30));
        label_60 = new QLabel(RunstateHelpPage);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(562, 2, 151, 191));
        label_60->setStyleSheet(QString::fromUtf8("border:2px solid white;"));
        label_60->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        label_61 = new QLabel(RunstateHelpPage);
        label_61->setObjectName(QString::fromUtf8("label_61"));
        label_61->setGeometry(QRect(570, 30, 91, 30));
        label_63 = new QLabel(RunstateHelpPage);
        label_63->setObjectName(QString::fromUtf8("label_63"));
        label_63->setGeometry(QRect(570, 60, 101, 30));
        label_64 = new QLabel(RunstateHelpPage);
        label_64->setObjectName(QString::fromUtf8("label_64"));
        label_64->setGeometry(QRect(570, 90, 63, 30));
        label_65 = new QLabel(RunstateHelpPage);
        label_65->setObjectName(QString::fromUtf8("label_65"));
        label_65->setGeometry(QRect(570, 120, 101, 30));
        label_62 = new QLabel(RunstateHelpPage);
        label_62->setObjectName(QString::fromUtf8("label_62"));
        label_62->setGeometry(QRect(570, 150, 51, 30));
        label_66 = new QLabel(RunstateHelpPage);
        label_66->setObjectName(QString::fromUtf8("label_66"));
        label_66->setGeometry(QRect(2, 367, 241, 81));
        label_66->setStyleSheet(QString::fromUtf8("border:2px solid white;\n"
""));
        label_66->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_67 = new QLabel(RunstateHelpPage);
        label_67->setObjectName(QString::fromUtf8("label_67"));
        label_67->setGeometry(QRect(290, 120, 51, 30));
        label_68 = new QLabel(RunstateHelpPage);
        label_68->setObjectName(QString::fromUtf8("label_68"));
        label_68->setGeometry(QRect(282, 244, 141, 41));
        label_68->setStyleSheet(QString::fromUtf8("border:2px solid white;"));
        label_68->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        label_70 = new QLabel(RunstateHelpPage);
        label_70->setObjectName(QString::fromUtf8("label_70"));
        label_70->setGeometry(QRect(150, 320, 81, 30));
        labelSignalSystem_4 = new QLabel(RunstateHelpPage);
        labelSignalSystem_4->setObjectName(QString::fromUtf8("labelSignalSystem_4"));
        labelSignalSystem_4->setGeometry(QRect(250, 320, 25, 25));
        labelSignalSystem_4->setStyleSheet(QString::fromUtf8("border-radius:12px;\n"
"background-color:red;\n"
"font:16px, \"SimHei\";\n"
""));
        labelSignalSystem_4->setAlignment(Qt::AlignCenter);
        label_72 = new QLabel(RunstateHelpPage);
        label_72->setObjectName(QString::fromUtf8("label_72"));
        label_72->setGeometry(QRect(142, 300, 141, 67));
        label_72->setStyleSheet(QString::fromUtf8("border:2px solid white;"));
        label_72->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        label_74 = new QLabel(RunstateHelpPage);
        label_74->setObjectName(QString::fromUtf8("label_74"));
        label_74->setGeometry(QRect(2, 272, 141, 95));
        label_74->setStyleSheet(QString::fromUtf8("border:2px solid white;"));
        label_74->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        label_75 = new QLabel(RunstateHelpPage);
        label_75->setObjectName(QString::fromUtf8("label_75"));
        label_75->setGeometry(QRect(10, 302, 121, 41));
        label_75->setStyleSheet(QString::fromUtf8("border:2px solid black;\n"
"color:black;\n"
"background-color:yellow;"));
        label_75->setAlignment(Qt::AlignCenter);
        label_76 = new QLabel(RunstateHelpPage);
        label_76->setObjectName(QString::fromUtf8("label_76"));
        label_76->setGeometry(QRect(282, 285, 141, 39));
        label_76->setStyleSheet(QString::fromUtf8("border:2px solid white;\n"
""));
        label_76->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_77 = new QLabel(RunstateHelpPage);
        label_77->setObjectName(QString::fromUtf8("label_77"));
        label_77->setGeometry(QRect(380, 290, 31, 31));
        label_77->setStyleSheet(QString::fromUtf8("image: url(:/image/fault.png);"));
        label_78 = new QLabel(RunstateHelpPage);
        label_78->setObjectName(QString::fromUtf8("label_78"));
        label_78->setGeometry(QRect(282, 323, 141, 45));
        label_78->setStyleSheet(QString::fromUtf8("border:2px solid white;\n"
""));
        label_78->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_79 = new QLabel(RunstateHelpPage);
        label_79->setObjectName(QString::fromUtf8("label_79"));
        label_79->setGeometry(QRect(712, 2, 88, 191));
        label_79->setStyleSheet(QString::fromUtf8("border:2px solid white;\n"
""));
        label_79->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        label_3 = new QLabel(RunstateHelpPage);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(735, 70, 41, 41));
        label_3->setStyleSheet(QString::fromUtf8("border-image: url(:/image/passageTalk.png);"));
        label_80 = new QLabel(RunstateHelpPage);
        label_80->setObjectName(QString::fromUtf8("label_80"));
        label_80->setGeometry(QRect(720, 20, 71, 41));
        label_80->setAlignment(Qt::AlignCenter);
        label_81 = new QLabel(RunstateHelpPage);
        label_81->setObjectName(QString::fromUtf8("label_81"));
        label_81->setGeometry(QRect(712, 191, 88, 198));
        label_81->setStyleSheet(QString::fromUtf8("border:2px solid white;\n"
""));
        label_81->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        label_82 = new QLabel(RunstateHelpPage);
        label_82->setObjectName(QString::fromUtf8("label_82"));
        label_82->setGeometry(QRect(735, 220, 41, 30));
        label_83 = new QLabel(RunstateHelpPage);
        label_83->setObjectName(QString::fromUtf8("label_83"));
        label_83->setGeometry(QRect(725, 290, 61, 30));
        label_4 = new QLabel(RunstateHelpPage);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(740, 245, 35, 35));
        label_4->setStyleSheet(QString::fromUtf8("border-image: url(:/image/trackbreak.png);"));
        label_5 = new QLabel(RunstateHelpPage);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(740, 320, 35, 35));
        label_5->setStyleSheet(QString::fromUtf8("border-image: url(:/image/OFFtrackbreak.png);"));
        labelSignalSystem_8 = new QLabel(RunstateHelpPage);
        labelSignalSystem_8->setObjectName(QString::fromUtf8("labelSignalSystem_8"));
        labelSignalSystem_8->setGeometry(QRect(370, 32, 25, 25));
        labelSignalSystem_8->setStyleSheet(QString::fromUtf8("border-image: url(:/image/closed.png);\n"
"font:16px, \"SimHei\";"));
        labelSignalSystem_8->setAlignment(Qt::AlignCenter);
        labelSignalSystem_9 = new QLabel(RunstateHelpPage);
        labelSignalSystem_9->setObjectName(QString::fromUtf8("labelSignalSystem_9"));
        labelSignalSystem_9->setGeometry(QRect(370, 62, 25, 25));
        labelSignalSystem_9->setStyleSheet(QString::fromUtf8("border-image: url(:/image/open.png);\n"
"font:16px, \"SimHei\";"));
        labelSignalSystem_9->setAlignment(Qt::AlignCenter);
        labelSignalSystem_10 = new QLabel(RunstateHelpPage);
        labelSignalSystem_10->setObjectName(QString::fromUtf8("labelSignalSystem_10"));
        labelSignalSystem_10->setGeometry(QRect(370, 92, 25, 25));
        labelSignalSystem_10->setStyleSheet(QString::fromUtf8("border-image: url(:/image/defect.png);\n"
"font:16px, \"SimHei\";"));
        labelSignalSystem_10->setAlignment(Qt::AlignCenter);
        labelSignalSystem_11 = new QLabel(RunstateHelpPage);
        labelSignalSystem_11->setObjectName(QString::fromUtf8("labelSignalSystem_11"));
        labelSignalSystem_11->setGeometry(QRect(370, 122, 25, 25));
        labelSignalSystem_11->setStyleSheet(QString::fromUtf8("border-image: url(:/image/HSCUnknown.jpg);\n"
"font:16px, \"SimHei\";"));
        labelSignalSystem_11->setAlignment(Qt::AlignCenter);
        label_89 = new QLabel(RunstateHelpPage);
        label_89->setObjectName(QString::fromUtf8("label_89"));
        label_89->setGeometry(QRect(570, 248, 51, 30));
        label_90 = new QLabel(RunstateHelpPage);
        label_90->setObjectName(QString::fromUtf8("label_90"));
        label_90->setGeometry(QRect(570, 218, 51, 30));
        label_91 = new QLabel(RunstateHelpPage);
        label_91->setObjectName(QString::fromUtf8("label_91"));
        label_91->setGeometry(QRect(562, 191, 151, 198));
        label_91->setStyleSheet(QString::fromUtf8("border:2px solid white;"));
        label_91->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        label_92 = new QLabel(RunstateHelpPage);
        label_92->setObjectName(QString::fromUtf8("label_92"));
        label_92->setGeometry(QRect(570, 310, 81, 30));
        label_93 = new QLabel(RunstateHelpPage);
        label_93->setObjectName(QString::fromUtf8("label_93"));
        label_93->setGeometry(QRect(570, 278, 51, 30));
        label_94 = new QLabel(RunstateHelpPage);
        label_94->setObjectName(QString::fromUtf8("label_94"));
        label_94->setGeometry(QRect(570, 340, 51, 30));
        labelSignalSystem_12 = new QLabel(RunstateHelpPage);
        labelSignalSystem_12->setObjectName(QString::fromUtf8("labelSignalSystem_12"));
        labelSignalSystem_12->setGeometry(QRect(680, 32, 25, 25));
        labelSignalSystem_12->setStyleSheet(QString::fromUtf8("border-image: url(:/image/acuWork.png);"));
        labelSignalSystem_12->setAlignment(Qt::AlignCenter);
        labelSignalSystem_13 = new QLabel(RunstateHelpPage);
        labelSignalSystem_13->setObjectName(QString::fromUtf8("labelSignalSystem_13"));
        labelSignalSystem_13->setGeometry(QRect(680, 92, 25, 25));
        labelSignalSystem_13->setStyleSheet(QString::fromUtf8("border-image: url(:/image/acuFault.png);"));
        labelSignalSystem_13->setAlignment(Qt::AlignCenter);
        labelSignalSystem_14 = new QLabel(RunstateHelpPage);
        labelSignalSystem_14->setObjectName(QString::fromUtf8("labelSignalSystem_14"));
        labelSignalSystem_14->setGeometry(QRect(680, 62, 25, 25));
        labelSignalSystem_14->setStyleSheet(QString::fromUtf8("border-image: url(:/image/acuDiswork.png);"));
        labelSignalSystem_14->setAlignment(Qt::AlignCenter);
        labelSignalSystem_15 = new QLabel(RunstateHelpPage);
        labelSignalSystem_15->setObjectName(QString::fromUtf8("labelSignalSystem_15"));
        labelSignalSystem_15->setGeometry(QRect(680, 122, 25, 25));
        labelSignalSystem_15->setStyleSheet(QString::fromUtf8("border-image: url(:/image/acuConnFault.png);"));
        labelSignalSystem_15->setAlignment(Qt::AlignCenter);
        labelSignalSystem_16 = new QLabel(RunstateHelpPage);
        labelSignalSystem_16->setObjectName(QString::fromUtf8("labelSignalSystem_16"));
        labelSignalSystem_16->setGeometry(QRect(680, 152, 25, 25));
        labelSignalSystem_16->setStyleSheet(QString::fromUtf8("border-image: url(:/image/acuUnknown.jpg);"));
        labelSignalSystem_16->setAlignment(Qt::AlignCenter);
        labelSignalSystem_17 = new QLabel(RunstateHelpPage);
        labelSignalSystem_17->setObjectName(QString::fromUtf8("labelSignalSystem_17"));
        labelSignalSystem_17->setGeometry(QRect(680, 220, 25, 25));
        labelSignalSystem_17->setStyleSheet(QString::fromUtf8("border-image: url(:/image/tcuWork.png);"));
        labelSignalSystem_17->setAlignment(Qt::AlignCenter);
        labelSignalSystem_18 = new QLabel(RunstateHelpPage);
        labelSignalSystem_18->setObjectName(QString::fromUtf8("labelSignalSystem_18"));
        labelSignalSystem_18->setGeometry(QRect(680, 310, 25, 25));
        labelSignalSystem_18->setStyleSheet(QString::fromUtf8("border-image: url(:/image/tcuConnFault.png);"));
        labelSignalSystem_18->setAlignment(Qt::AlignCenter);
        labelSignalSystem_19 = new QLabel(RunstateHelpPage);
        labelSignalSystem_19->setObjectName(QString::fromUtf8("labelSignalSystem_19"));
        labelSignalSystem_19->setGeometry(QRect(680, 280, 25, 25));
        labelSignalSystem_19->setStyleSheet(QString::fromUtf8("border-image: url(:/image/tcuLock.png);"));
        labelSignalSystem_19->setAlignment(Qt::AlignCenter);
        labelSignalSystem_20 = new QLabel(RunstateHelpPage);
        labelSignalSystem_20->setObjectName(QString::fromUtf8("labelSignalSystem_20"));
        labelSignalSystem_20->setGeometry(QRect(680, 250, 25, 25));
        labelSignalSystem_20->setStyleSheet(QString::fromUtf8("border-image: url(:/image/tcuFault.png);"));
        labelSignalSystem_20->setAlignment(Qt::AlignCenter);
        labelSignalSystem_21 = new QLabel(RunstateHelpPage);
        labelSignalSystem_21->setObjectName(QString::fromUtf8("labelSignalSystem_21"));
        labelSignalSystem_21->setGeometry(QRect(680, 340, 25, 25));
        labelSignalSystem_21->setStyleSheet(QString::fromUtf8("border-image: url(:/image/tcuUnknown.jpg);"));
        labelSignalSystem_21->setAlignment(Qt::AlignCenter);
        labelSignalSystem_22 = new QLabel(RunstateHelpPage);
        labelSignalSystem_22->setObjectName(QString::fromUtf8("labelSignalSystem_22"));
        labelSignalSystem_22->setGeometry(QRect(520, 300, 25, 25));
        labelSignalSystem_22->setStyleSheet(QString::fromUtf8("border-image: url(:/image/brakeRelease.png);"));
        labelSignalSystem_22->setAlignment(Qt::AlignCenter);
        labelSignalSystem_23 = new QLabel(RunstateHelpPage);
        labelSignalSystem_23->setObjectName(QString::fromUtf8("labelSignalSystem_23"));
        labelSignalSystem_23->setGeometry(QRect(520, 390, 25, 25));
        labelSignalSystem_23->setStyleSheet(QString::fromUtf8("border-image: url(:/image/brakeReleaseNotOK.png);"));
        labelSignalSystem_23->setAlignment(Qt::AlignCenter);
        labelSignalSystem_24 = new QLabel(RunstateHelpPage);
        labelSignalSystem_24->setObjectName(QString::fromUtf8("labelSignalSystem_24"));
        labelSignalSystem_24->setGeometry(QRect(520, 360, 25, 25));
        labelSignalSystem_24->setStyleSheet(QString::fromUtf8("border-image: url(:/image/brakeCut.png);"));
        labelSignalSystem_24->setAlignment(Qt::AlignCenter);
        labelSignalSystem_25 = new QLabel(RunstateHelpPage);
        labelSignalSystem_25->setObjectName(QString::fromUtf8("labelSignalSystem_25"));
        labelSignalSystem_25->setGeometry(QRect(520, 330, 25, 25));
        labelSignalSystem_25->setStyleSheet(QString::fromUtf8("border-image: url(:/image/brakeApplyOK.png);"));
        labelSignalSystem_25->setAlignment(Qt::AlignCenter);
        labelSignalSystem_26 = new QLabel(RunstateHelpPage);
        labelSignalSystem_26->setObjectName(QString::fromUtf8("labelSignalSystem_26"));
        labelSignalSystem_26->setGeometry(QRect(520, 420, 25, 25));
        labelSignalSystem_26->setStyleSheet(QString::fromUtf8("border-image: url(:/image/brakeUnknown.jpg);"));
        labelSignalSystem_26->setAlignment(Qt::AlignCenter);
        label_95 = new QLabel(RunstateHelpPage);
        label_95->setObjectName(QString::fromUtf8("label_95"));
        label_95->setGeometry(QRect(242, 367, 181, 81));
        label_95->setStyleSheet(QString::fromUtf8("border:2px solid white;\n"
""));
        label_95->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelBattery = new QLabel(RunstateHelpPage);
        labelBattery->setObjectName(QString::fromUtf8("labelBattery"));
        labelBattery->setGeometry(QRect(366, 386, 41, 45));
        labelBattery->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);\n"
"border:2px solid black;\n"
"color:black;\n"
"font:12px;"));
        labelBattery->setAlignment(Qt::AlignCenter);
        labelBatteryP = new QLabel(RunstateHelpPage);
        labelBatteryP->setObjectName(QString::fromUtf8("labelBatteryP"));
        labelBatteryP->setGeometry(QRect(377, 377, 5, 20));
        labelBatteryP->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        label_14 = new QLabel(RunstateHelpPage);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(387, 390, 16, 16));
        label_14->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);\n"
"font: 75 12pt \"SimHei\";\n"
"border:0px;\n"
"color:black;"));
        label_14->setAlignment(Qt::AlignCenter);
        labelBatteryN = new QLabel(RunstateHelpPage);
        labelBatteryN->setObjectName(QString::fromUtf8("labelBatteryN"));
        labelBatteryN->setGeometry(QRect(392, 377, 5, 20));
        labelBatteryN->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        label_13 = new QLabel(RunstateHelpPage);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(370, 390, 16, 16));
        label_13->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);\n"
"font: 75 12pt \"SimHei\";\n"
"border:0px;\n"
"color:black;"));
        label_13->setAlignment(Qt::AlignCenter);
        labelBatteryTemperature = new QLabel(RunstateHelpPage);
        labelBatteryTemperature->setObjectName(QString::fromUtf8("labelBatteryTemperature"));
        labelBatteryTemperature->setGeometry(QRect(376, 413, 25, 16));
        labelBatteryTemperature->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);\n"
"border:0px;\n"
"color:black;\n"
"font:12px;"));
        labelBatteryTemperature->setAlignment(Qt::AlignCenter);
        labelBatteryTemperature_2 = new QLabel(RunstateHelpPage);
        labelBatteryTemperature_2->setObjectName(QString::fromUtf8("labelBatteryTemperature_2"));
        labelBatteryTemperature_2->setGeometry(QRect(376, 399, 25, 16));
        labelBatteryTemperature_2->setStyleSheet(QString::fromUtf8("background-color: rgb(234, 234, 234);\n"
"border:0px;\n"
"color:black;\n"
"font:12px;"));
        labelBatteryTemperature_2->setAlignment(Qt::AlignCenter);
        labelRP = new QLabel(RunstateHelpPage);
        labelRP->setObjectName(QString::fromUtf8("labelRP"));
        labelRP->setGeometry(QRect(380, 326, 35, 35));
        labelRP->setStyleSheet(QString::fromUtf8("border-image: url(:/image/tracking.png);\n"
""));
        labelRP->setAlignment(Qt::AlignCenter);
        labelSignalSystem_7 = new QLabel(RunstateHelpPage);
        labelSignalSystem_7->setObjectName(QString::fromUtf8("labelSignalSystem_7"));
        labelSignalSystem_7->setGeometry(QRect(385, 250, 31, 31));
        labelSignalSystem_7->setStyleSheet(QString::fromUtf8("border-image: url(:/image/maintain.PNG);\n"
""));
        labelSignalSystem_7->setAlignment(Qt::AlignCenter);
        labelSignalSystem_27 = new QLabel(RunstateHelpPage);
        labelSignalSystem_27->setObjectName(QString::fromUtf8("labelSignalSystem_27"));
        labelSignalSystem_27->setGeometry(QRect(240, 120, 25, 25));
        labelSignalSystem_27->setStyleSheet(QString::fromUtf8("background-color:grey;"));
        labelSignalSystem_27->setAlignment(Qt::AlignCenter);
        labelSignalSystem_28 = new QLabel(RunstateHelpPage);
        labelSignalSystem_28->setObjectName(QString::fromUtf8("labelSignalSystem_28"));
        labelSignalSystem_28->setGeometry(QRect(240, 90, 25, 25));
        labelSignalSystem_28->setStyleSheet(QString::fromUtf8("border-image: url(:/image/doorOpen.png);"));
        labelSignalSystem_28->setAlignment(Qt::AlignCenter);
        labelSignalSystem_29 = new QLabel(RunstateHelpPage);
        labelSignalSystem_29->setObjectName(QString::fromUtf8("labelSignalSystem_29"));
        labelSignalSystem_29->setGeometry(QRect(240, 60, 25, 25));
        labelSignalSystem_29->setStyleSheet(QString::fromUtf8("border-image: url(:/image/doorOpenError.png);"));
        labelSignalSystem_29->setAlignment(Qt::AlignCenter);
        labelSignalSystem_30 = new QLabel(RunstateHelpPage);
        labelSignalSystem_30->setObjectName(QString::fromUtf8("labelSignalSystem_30"));
        labelSignalSystem_30->setGeometry(QRect(240, 150, 25, 25));
        labelSignalSystem_30->setStyleSheet(QString::fromUtf8("border-image: url(:/image/doorBlock.png);"));
        labelSignalSystem_30->setAlignment(Qt::AlignCenter);
        labelSignalSystem_31 = new QLabel(RunstateHelpPage);
        labelSignalSystem_31->setObjectName(QString::fromUtf8("labelSignalSystem_31"));
        labelSignalSystem_31->setGeometry(QRect(240, 30, 25, 25));
        labelSignalSystem_31->setStyleSheet(QString::fromUtf8("border-image: url(:/image/closeDoor.png);"));
        labelSignalSystem_31->setAlignment(Qt::AlignCenter);
        labelSignalSystem_32 = new QLabel(RunstateHelpPage);
        labelSignalSystem_32->setObjectName(QString::fromUtf8("labelSignalSystem_32"));
        labelSignalSystem_32->setGeometry(QRect(240, 270, 25, 25));
        labelSignalSystem_32->setStyleSheet(QString::fromUtf8("border-image: url(:/image/panConnFault.png);"));
        labelSignalSystem_32->setAlignment(Qt::AlignCenter);
        labelSignalSystem_33 = new QLabel(RunstateHelpPage);
        labelSignalSystem_33->setObjectName(QString::fromUtf8("labelSignalSystem_33"));
        labelSignalSystem_33->setGeometry(QRect(240, 210, 25, 25));
        labelSignalSystem_33->setStyleSheet(QString::fromUtf8("border-image: url(:/image/cut.png);"));
        labelSignalSystem_33->setAlignment(Qt::AlignCenter);
        labelSignalSystem_34 = new QLabel(RunstateHelpPage);
        labelSignalSystem_34->setObjectName(QString::fromUtf8("labelSignalSystem_34"));
        labelSignalSystem_34->setGeometry(QRect(240, 180, 25, 25));
        labelSignalSystem_34->setStyleSheet(QString::fromUtf8("border-image: url(:/image/doorFault.png);"));
        labelSignalSystem_34->setAlignment(Qt::AlignCenter);
        labelSignalSystem_35 = new QLabel(RunstateHelpPage);
        labelSignalSystem_35->setObjectName(QString::fromUtf8("labelSignalSystem_35"));
        labelSignalSystem_35->setGeometry(QRect(240, 240, 25, 25));
        labelSignalSystem_35->setStyleSheet(QString::fromUtf8("background-color:yellow;"));
        labelSignalSystem_35->setAlignment(Qt::AlignCenter);
        labelSignalSystem_36 = new QLabel(RunstateHelpPage);
        labelSignalSystem_36->setObjectName(QString::fromUtf8("labelSignalSystem_36"));
        labelSignalSystem_36->setGeometry(QRect(110, 150, 25, 25));
        labelSignalSystem_36->setStyleSheet(QString::fromUtf8("border-image: url(:/image/upFault.png);"));
        labelSignalSystem_36->setAlignment(Qt::AlignCenter);
        labelSignalSystem_37 = new QLabel(RunstateHelpPage);
        labelSignalSystem_37->setObjectName(QString::fromUtf8("labelSignalSystem_37"));
        labelSignalSystem_37->setGeometry(QRect(110, 90, 25, 25));
        labelSignalSystem_37->setStyleSheet(QString::fromUtf8("border-image: url(:/image/LowPosition.png);"));
        labelSignalSystem_37->setAlignment(Qt::AlignCenter);
        labelSignalSystem_38 = new QLabel(RunstateHelpPage);
        labelSignalSystem_38->setObjectName(QString::fromUtf8("labelSignalSystem_38"));
        labelSignalSystem_38->setGeometry(QRect(110, 180, 25, 25));
        labelSignalSystem_38->setStyleSheet(QString::fromUtf8("border-image: url(:/image/upLock.png);"));
        labelSignalSystem_38->setAlignment(Qt::AlignCenter);
        labelSignalSystem_39 = new QLabel(RunstateHelpPage);
        labelSignalSystem_39->setObjectName(QString::fromUtf8("labelSignalSystem_39"));
        labelSignalSystem_39->setGeometry(QRect(110, 60, 25, 25));
        labelSignalSystem_39->setStyleSheet(QString::fromUtf8("border-image: url(:/image/upMid.png);"));
        labelSignalSystem_39->setAlignment(Qt::AlignCenter);
        labelSignalSystem_40 = new QLabel(RunstateHelpPage);
        labelSignalSystem_40->setObjectName(QString::fromUtf8("labelSignalSystem_40"));
        labelSignalSystem_40->setGeometry(QRect(110, 120, 25, 25));
        labelSignalSystem_40->setStyleSheet(QString::fromUtf8("border-image: url(:/image/downFault.png);"));
        labelSignalSystem_40->setAlignment(Qt::AlignCenter);
        labelSignalSystem_41 = new QLabel(RunstateHelpPage);
        labelSignalSystem_41->setObjectName(QString::fromUtf8("labelSignalSystem_41"));
        labelSignalSystem_41->setGeometry(QRect(110, 210, 25, 25));
        labelSignalSystem_41->setStyleSheet(QString::fromUtf8("border-image: url(:/image/downLock.png);"));
        labelSignalSystem_41->setAlignment(Qt::AlignCenter);
        labelSignalSystem_42 = new QLabel(RunstateHelpPage);
        labelSignalSystem_42->setObjectName(QString::fromUtf8("labelSignalSystem_42"));
        labelSignalSystem_42->setGeometry(QRect(110, 240, 25, 25));
        labelSignalSystem_42->setStyleSheet(QString::fromUtf8("border-image: url(:/image/panConnFault.png);"));
        labelSignalSystem_42->setAlignment(Qt::AlignCenter);
        labelSignalSystem_43 = new QLabel(RunstateHelpPage);
        labelSignalSystem_43->setObjectName(QString::fromUtf8("labelSignalSystem_43"));
        labelSignalSystem_43->setGeometry(QRect(110, 30, 25, 25));
        labelSignalSystem_43->setStyleSheet(QString::fromUtf8("border-image: url(:/image/up.png);"));
        labelSignalSystem_43->setAlignment(Qt::AlignCenter);
        label_97 = new QLabel(RunstateHelpPage);
        label_97->setObjectName(QString::fromUtf8("label_97"));
        label_97->setGeometry(QRect(570, 218, 51, 30));
        label_98 = new QLabel(RunstateHelpPage);
        label_98->setObjectName(QString::fromUtf8("label_98"));
        label_98->setGeometry(QRect(570, 250, 51, 30));
        labelSignalSystem_44 = new QLabel(RunstateHelpPage);
        labelSignalSystem_44->setObjectName(QString::fromUtf8("labelSignalSystem_44"));
        labelSignalSystem_44->setGeometry(QRect(150, 390, 21, 35));
        labelSignalSystem_44->setStyleSheet(QString::fromUtf8("border-image: url(:/image/keyActive.PNG);"));
        labelSignalSystem_44->setAlignment(Qt::AlignCenter);
        labelSignalSystem_45 = new QLabel(RunstateHelpPage);
        labelSignalSystem_45->setObjectName(QString::fromUtf8("labelSignalSystem_45"));
        labelSignalSystem_45->setGeometry(QRect(200, 390, 21, 35));
        labelSignalSystem_45->setStyleSheet(QString::fromUtf8("border-image: url(:/image/keyActive2.PNG);"));
        labelSignalSystem_45->setAlignment(Qt::AlignCenter);
        label_71 = new QLabel(RunstateHelpPage);
        label_71->setObjectName(QString::fromUtf8("label_71"));
        label_71->setGeometry(QRect(290, 250, 81, 30));
        label_49 = new QLabel(RunstateHelpPage);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(430, 90, 71, 30));
        label_50 = new QLabel(RunstateHelpPage);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(430, 120, 71, 30));
        label_51 = new QLabel(RunstateHelpPage);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(430, 150, 71, 30));
        label_69 = new QLabel(RunstateHelpPage);
        label_69->setObjectName(QString::fromUtf8("label_69"));
        label_69->setGeometry(QRect(430, 177, 91, 30));
        label_69->setStyleSheet(QString::fromUtf8("font:17px;"));
        label_73 = new QLabel(RunstateHelpPage);
        label_73->setObjectName(QString::fromUtf8("label_73"));
        label_73->setGeometry(QRect(430, 207, 91, 30));
        label_73->setStyleSheet(QString::fromUtf8("font:17px;"));
        labelSignalSystem_46 = new QLabel(RunstateHelpPage);
        labelSignalSystem_46->setObjectName(QString::fromUtf8("labelSignalSystem_46"));
        labelSignalSystem_46->setGeometry(QRect(530, 60, 25, 25));
        labelSignalSystem_46->setStyleSheet(QString::fromUtf8("border-image: url(:/image/battaryAfault.png);"));
        labelSignalSystem_46->setAlignment(Qt::AlignCenter);
        labelSignalSystem_47 = new QLabel(RunstateHelpPage);
        labelSignalSystem_47->setObjectName(QString::fromUtf8("labelSignalSystem_47"));
        labelSignalSystem_47->setGeometry(QRect(530, 30, 25, 25));
        labelSignalSystem_47->setStyleSheet(QString::fromUtf8("border-image: url(:/image/battaryWork.png);"));
        labelSignalSystem_47->setAlignment(Qt::AlignCenter);
        labelSignalSystem_48 = new QLabel(RunstateHelpPage);
        labelSignalSystem_48->setObjectName(QString::fromUtf8("labelSignalSystem_48"));
        labelSignalSystem_48->setGeometry(QRect(530, 210, 25, 25));
        labelSignalSystem_48->setStyleSheet(QString::fromUtf8("border-image: url(:/image/battaryBconnF.png);"));
        labelSignalSystem_48->setAlignment(Qt::AlignCenter);
        labelSignalSystem_49 = new QLabel(RunstateHelpPage);
        labelSignalSystem_49->setObjectName(QString::fromUtf8("labelSignalSystem_49"));
        labelSignalSystem_49->setGeometry(QRect(530, 180, 25, 25));
        labelSignalSystem_49->setStyleSheet(QString::fromUtf8("border-image: url(:/image/battaryAconnF.png);"));
        labelSignalSystem_49->setAlignment(Qt::AlignCenter);
        labelSignalSystem_50 = new QLabel(RunstateHelpPage);
        labelSignalSystem_50->setObjectName(QString::fromUtf8("labelSignalSystem_50"));
        labelSignalSystem_50->setGeometry(QRect(530, 150, 25, 25));
        labelSignalSystem_50->setStyleSheet(QString::fromUtf8("border-image: url(:/image/battaryBcut.png);"));
        labelSignalSystem_50->setAlignment(Qt::AlignCenter);
        labelSignalSystem_51 = new QLabel(RunstateHelpPage);
        labelSignalSystem_51->setObjectName(QString::fromUtf8("labelSignalSystem_51"));
        labelSignalSystem_51->setGeometry(QRect(530, 90, 25, 25));
        labelSignalSystem_51->setStyleSheet(QString::fromUtf8("border-image: url(:/image/battaryBfault.png);"));
        labelSignalSystem_51->setAlignment(Qt::AlignCenter);
        labelSignalSystem_52 = new QLabel(RunstateHelpPage);
        labelSignalSystem_52->setObjectName(QString::fromUtf8("labelSignalSystem_52"));
        labelSignalSystem_52->setGeometry(QRect(530, 120, 25, 25));
        labelSignalSystem_52->setStyleSheet(QString::fromUtf8("border-image: url(:/image/battaryAcut.png);"));
        labelSignalSystem_52->setAlignment(Qt::AlignCenter);
        label_84 = new QLabel(RunstateHelpPage);
        label_84->setObjectName(QString::fromUtf8("label_84"));
        label_84->setGeometry(QRect(562, 389, 237, 61));
        label_84->setStyleSheet(QString::fromUtf8("border:2px solid white;"));
        label_84->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        label_85 = new QLabel(RunstateHelpPage);
        label_85->setObjectName(QString::fromUtf8("label_85"));
        label_85->setGeometry(QRect(570, 405, 81, 30));
        labelSignalSystem_5 = new QLabel(RunstateHelpPage);
        labelSignalSystem_5->setObjectName(QString::fromUtf8("labelSignalSystem_5"));
        labelSignalSystem_5->setGeometry(QRect(730, 400, 41, 41));
        labelSignalSystem_5->setStyleSheet(QString::fromUtf8("border-image: url(:/image/motorAllow.gif);\n"
""));
        labelSignalSystem_5->setAlignment(Qt::AlignCenter);
        label_86 = new QLabel(RunstateHelpPage);
        label_86->setObjectName(QString::fromUtf8("label_86"));
        label_86->setGeometry(QRect(430, 237, 91, 30));
        label_86->setStyleSheet(QString::fromUtf8("font:17px;"));
        labelSignalSystem_53 = new QLabel(RunstateHelpPage);
        labelSignalSystem_53->setObjectName(QString::fromUtf8("labelSignalSystem_53"));
        labelSignalSystem_53->setGeometry(QRect(530, 240, 25, 25));
        labelSignalSystem_53->setStyleSheet(QString::fromUtf8("border-image: url(:/image/battaryConnF.png);"));
        labelSignalSystem_53->setAlignment(Qt::AlignCenter);
        label_95->raise();
        labelBatteryN->raise();
        label_72->raise();
        label_22->raise();
        labelSignalSystem->raise();
        labelSignalSystem_2->raise();
        label_23->raise();
        label_24->raise();
        label_25->raise();
        label_26->raise();
        label_27->raise();
        label_28->raise();
        label_29->raise();
        label_30->raise();
        label_31->raise();
        label_32->raise();
        label_33->raise();
        label_34->raise();
        label_35->raise();
        label_36->raise();
        label_37->raise();
        label_38->raise();
        label_39->raise();
        label_40->raise();
        label_41->raise();
        label_42->raise();
        label_43->raise();
        label_44->raise();
        label_45->raise();
        label_46->raise();
        label_47->raise();
        label_48->raise();
        label_52->raise();
        label_53->raise();
        label_54->raise();
        label_55->raise();
        label_56->raise();
        label_57->raise();
        label_58->raise();
        label_59->raise();
        label_60->raise();
        label_61->raise();
        label_63->raise();
        label_64->raise();
        label_65->raise();
        label_62->raise();
        label_66->raise();
        label_67->raise();
        label_68->raise();
        label_70->raise();
        labelSignalSystem_4->raise();
        label_74->raise();
        label_75->raise();
        label_76->raise();
        label_77->raise();
        label_78->raise();
        label_79->raise();
        label_3->raise();
        label_80->raise();
        label_81->raise();
        label_82->raise();
        label_83->raise();
        label_4->raise();
        label_5->raise();
        labelSignalSystem_8->raise();
        labelSignalSystem_9->raise();
        labelSignalSystem_10->raise();
        labelSignalSystem_11->raise();
        label_89->raise();
        label_90->raise();
        label_91->raise();
        label_92->raise();
        label_93->raise();
        label_94->raise();
        labelSignalSystem_12->raise();
        labelSignalSystem_13->raise();
        labelSignalSystem_14->raise();
        labelSignalSystem_15->raise();
        labelSignalSystem_16->raise();
        labelSignalSystem_17->raise();
        labelSignalSystem_18->raise();
        labelSignalSystem_19->raise();
        labelSignalSystem_20->raise();
        labelSignalSystem_21->raise();
        labelSignalSystem_22->raise();
        labelSignalSystem_23->raise();
        labelSignalSystem_24->raise();
        labelSignalSystem_25->raise();
        labelSignalSystem_26->raise();
        labelBattery->raise();
        labelBatteryP->raise();
        label_14->raise();
        label_13->raise();
        labelBatteryTemperature->raise();
        labelBatteryTemperature_2->raise();
        labelRP->raise();
        labelSignalSystem_7->raise();
        labelSignalSystem_27->raise();
        labelSignalSystem_28->raise();
        labelSignalSystem_29->raise();
        labelSignalSystem_30->raise();
        labelSignalSystem_31->raise();
        labelSignalSystem_32->raise();
        labelSignalSystem_33->raise();
        labelSignalSystem_34->raise();
        labelSignalSystem_35->raise();
        labelSignalSystem_36->raise();
        labelSignalSystem_37->raise();
        labelSignalSystem_38->raise();
        labelSignalSystem_39->raise();
        labelSignalSystem_40->raise();
        labelSignalSystem_41->raise();
        labelSignalSystem_42->raise();
        labelSignalSystem_43->raise();
        label_97->raise();
        label_98->raise();
        labelSignalSystem_44->raise();
        labelSignalSystem_45->raise();
        label_71->raise();
        label_49->raise();
        label_50->raise();
        label_51->raise();
        label_69->raise();
        label_73->raise();
        labelSignalSystem_46->raise();
        labelSignalSystem_47->raise();
        labelSignalSystem_48->raise();
        labelSignalSystem_49->raise();
        labelSignalSystem_50->raise();
        labelSignalSystem_51->raise();
        labelSignalSystem_52->raise();
        label_84->raise();
        label_85->raise();
        labelSignalSystem_5->raise();
        label_86->raise();
        labelSignalSystem_53->raise();

        retranslateUi(RunstateHelpPage);

        QMetaObject::connectSlotsByName(RunstateHelpPage);
    } // setupUi

    void retranslateUi(QWidget *RunstateHelpPage)
    {
        RunstateHelpPage->setWindowTitle(QApplication::translate("RunstateHelpPage", "Form", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("RunstateHelpPage", "\344\277\241\345\217\267\347\263\273\347\273\237", 0, QApplication::UnicodeUTF8));
        labelSignalSystem->setText(QString());
        labelSignalSystem_2->setText(QString());
        label_23->setText(QApplication::translate("RunstateHelpPage", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("RunstateHelpPage", "\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("RunstateHelpPage", "\345\217\227\347\224\265\345\274\223", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("RunstateHelpPage", "\345\215\207\350\265\267", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("RunstateHelpPage", "\345\215\207/\351\231\215\344\270\255", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("RunstateHelpPage", "\351\231\215\344\270\213", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("RunstateHelpPage", "\351\231\215\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("RunstateHelpPage", "\345\215\207\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("RunstateHelpPage", "\345\215\207\351\224\201\351\227\255", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("RunstateHelpPage", "\351\231\215\351\224\201\351\227\255", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("RunstateHelpPage", "\350\275\246\351\227\250", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("RunstateHelpPage", "\345\205\263\345\245\275", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("RunstateHelpPage", "\346\234\252\345\205\263\345\245\275", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("RunstateHelpPage", "\345\274\200", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("RunstateHelpPage", "\351\200\232\350\256\257\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        label_38->setText(QApplication::translate("RunstateHelpPage", "\351\232\234\347\242\215\347\211\251", 0, QApplication::UnicodeUTF8));
        label_39->setText(QApplication::translate("RunstateHelpPage", "\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("RunstateHelpPage", "\351\232\224\347\246\273", 0, QApplication::UnicodeUTF8));
        label_41->setText(QApplication::translate("RunstateHelpPage", "\347\264\247\346\200\245\350\247\243\351\224\201", 0, QApplication::UnicodeUTF8));
        label_42->setText(QApplication::translate("RunstateHelpPage", "\351\253\230\351\200\237\346\226\255\350\267\257\345\231\250", 0, QApplication::UnicodeUTF8));
        label_43->setText(QApplication::translate("RunstateHelpPage", "\351\227\255\345\220\210", 0, QApplication::UnicodeUTF8));
        label_44->setText(QApplication::translate("RunstateHelpPage", "\346\226\255\345\274\200", 0, QApplication::UnicodeUTF8));
        label_45->setText(QApplication::translate("RunstateHelpPage", "\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        label_46->setText(QApplication::translate("RunstateHelpPage", "\350\266\205\347\272\247\347\224\265\345\256\271", 0, QApplication::UnicodeUTF8));
        label_47->setText(QApplication::translate("RunstateHelpPage", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        label_48->setText(QApplication::translate("RunstateHelpPage", "A\350\267\257\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        label_52->setText(QApplication::translate("RunstateHelpPage", "\346\234\252\347\237\245", 0, QApplication::UnicodeUTF8));
        label_53->setText(QApplication::translate("RunstateHelpPage", "\346\234\252\347\237\245", 0, QApplication::UnicodeUTF8));
        label_54->setText(QApplication::translate("RunstateHelpPage", "\345\210\266\345\212\250", 0, QApplication::UnicodeUTF8));
        label_55->setText(QApplication::translate("RunstateHelpPage", "\347\274\223\350\247\243", 0, QApplication::UnicodeUTF8));
        label_56->setText(QApplication::translate("RunstateHelpPage", "\346\226\275\345\212\240", 0, QApplication::UnicodeUTF8));
        label_57->setText(QApplication::translate("RunstateHelpPage", "\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        label_58->setText(QApplication::translate("RunstateHelpPage", "\351\232\224\347\246\273", 0, QApplication::UnicodeUTF8));
        label_59->setText(QApplication::translate("RunstateHelpPage", "\346\234\252\347\237\245", 0, QApplication::UnicodeUTF8));
        label_60->setText(QApplication::translate("RunstateHelpPage", "\350\276\205\345\212\251", 0, QApplication::UnicodeUTF8));
        label_61->setText(QApplication::translate("RunstateHelpPage", "\346\255\243\345\270\270\345\267\245\344\275\234", 0, QApplication::UnicodeUTF8));
        label_63->setText(QApplication::translate("RunstateHelpPage", "\346\255\243\345\270\270\346\234\252\345\267\245\344\275\234", 0, QApplication::UnicodeUTF8));
        label_64->setText(QApplication::translate("RunstateHelpPage", "\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        label_65->setText(QApplication::translate("RunstateHelpPage", "\351\200\232\344\277\241\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        label_62->setText(QApplication::translate("RunstateHelpPage", "\346\234\252\347\237\245", 0, QApplication::UnicodeUTF8));
        label_66->setText(QApplication::translate("RunstateHelpPage", "\350\275\246\351\222\245\345\214\231\346\277\200\346\264\273", 0, QApplication::UnicodeUTF8));
        label_67->setText(QApplication::translate("RunstateHelpPage", "\346\234\252\347\237\245", 0, QApplication::UnicodeUTF8));
        label_68->setText(QString());
        label_70->setText(QApplication::translate("RunstateHelpPage", "\347\264\247\346\200\245\345\210\266\345\212\250", 0, QApplication::UnicodeUTF8));
        labelSignalSystem_4->setText(QApplication::translate("RunstateHelpPage", "EB", 0, QApplication::UnicodeUTF8));
        label_72->setText(QString());
        label_74->setText(QApplication::translate("RunstateHelpPage", "\351\231\220\351\200\237\346\240\207\350\257\206", 0, QApplication::UnicodeUTF8));
        label_75->setText(QApplication::translate("RunstateHelpPage", "\351\231\220\351\200\23740km/h", 0, QApplication::UnicodeUTF8));
        label_76->setText(QApplication::translate("RunstateHelpPage", "\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        label_77->setText(QString());
        label_78->setText(QApplication::translate("RunstateHelpPage", "\346\213\226\346\213\275\346\250\241\345\274\217", 0, QApplication::UnicodeUTF8));
        label_79->setText(QString());
        label_3->setText(QString());
        label_80->setText(QApplication::translate("RunstateHelpPage", "\344\270\216\344\271\230\345\256\242\n"
"\345\257\271\350\256\262", 0, QApplication::UnicodeUTF8));
        label_81->setText(QApplication::translate("RunstateHelpPage", "\347\243\201\350\275\250\345\210\266\345\212\250", 0, QApplication::UnicodeUTF8));
        label_82->setText(QApplication::translate("RunstateHelpPage", "\346\226\275\345\212\240", 0, QApplication::UnicodeUTF8));
        label_83->setText(QApplication::translate("RunstateHelpPage", "\346\234\252\346\226\275\345\212\240", 0, QApplication::UnicodeUTF8));
        label_4->setText(QString());
        label_5->setText(QString());
        labelSignalSystem_8->setText(QString());
        labelSignalSystem_9->setText(QString());
        labelSignalSystem_10->setText(QString());
        labelSignalSystem_11->setText(QString());
        label_89->setText(QApplication::translate("RunstateHelpPage", "\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        label_90->setText(QApplication::translate("RunstateHelpPage", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        label_91->setText(QApplication::translate("RunstateHelpPage", "\347\211\265\345\274\225", 0, QApplication::UnicodeUTF8));
        label_92->setText(QApplication::translate("RunstateHelpPage", "\351\200\232\344\277\241\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        label_93->setText(QApplication::translate("RunstateHelpPage", "\351\224\201\351\227\255", 0, QApplication::UnicodeUTF8));
        label_94->setText(QApplication::translate("RunstateHelpPage", "\346\234\252\347\237\245", 0, QApplication::UnicodeUTF8));
        labelSignalSystem_12->setText(QString());
        labelSignalSystem_13->setText(QString());
        labelSignalSystem_14->setText(QString());
        labelSignalSystem_15->setText(QString());
        labelSignalSystem_16->setText(QString());
        labelSignalSystem_17->setText(QString());
        labelSignalSystem_18->setText(QString());
        labelSignalSystem_19->setText(QString());
        labelSignalSystem_20->setText(QString());
        labelSignalSystem_21->setText(QString());
        labelSignalSystem_22->setText(QString());
        labelSignalSystem_23->setText(QString());
        labelSignalSystem_24->setText(QString());
        labelSignalSystem_25->setText(QString());
        labelSignalSystem_26->setText(QString());
        label_95->setText(QApplication::translate("RunstateHelpPage", "\350\223\204\347\224\265\346\261\240", 0, QApplication::UnicodeUTF8));
        labelBattery->setText(QString());
        labelBatteryP->setText(QString());
        label_14->setText(QApplication::translate("RunstateHelpPage", "-", 0, QApplication::UnicodeUTF8));
        labelBatteryN->setText(QString());
        label_13->setText(QApplication::translate("RunstateHelpPage", "+", 0, QApplication::UnicodeUTF8));
        labelBatteryTemperature->setText(QApplication::translate("RunstateHelpPage", "34\342\204\203", 0, QApplication::UnicodeUTF8));
        labelBatteryTemperature_2->setText(QApplication::translate("RunstateHelpPage", "0V", 0, QApplication::UnicodeUTF8));
        labelRP->setText(QString());
        labelSignalSystem_7->setText(QString());
        labelSignalSystem_27->setText(QString());
        labelSignalSystem_28->setText(QString());
        labelSignalSystem_29->setText(QString());
        labelSignalSystem_30->setText(QString());
        labelSignalSystem_31->setText(QString());
        labelSignalSystem_32->setText(QString());
        labelSignalSystem_33->setText(QString());
        labelSignalSystem_34->setText(QString());
        labelSignalSystem_35->setText(QString());
        labelSignalSystem_36->setText(QString());
        labelSignalSystem_37->setText(QString());
        labelSignalSystem_38->setText(QString());
        labelSignalSystem_39->setText(QString());
        labelSignalSystem_40->setText(QString());
        labelSignalSystem_41->setText(QString());
        labelSignalSystem_42->setText(QString());
        labelSignalSystem_43->setText(QString());
        label_97->setText(QApplication::translate("RunstateHelpPage", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        label_98->setText(QApplication::translate("RunstateHelpPage", "\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        labelSignalSystem_44->setText(QString());
        labelSignalSystem_45->setText(QString());
        label_71->setText(QApplication::translate("RunstateHelpPage", "\346\243\200\344\277\256\346\250\241\345\274\217", 0, QApplication::UnicodeUTF8));
        label_49->setText(QApplication::translate("RunstateHelpPage", "B\350\267\257\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        label_50->setText(QApplication::translate("RunstateHelpPage", "A\350\267\257\351\232\224\347\246\273", 0, QApplication::UnicodeUTF8));
        label_51->setText(QApplication::translate("RunstateHelpPage", "B\350\267\257\351\232\224\347\246\273", 0, QApplication::UnicodeUTF8));
        label_69->setText(QApplication::translate("RunstateHelpPage", "A\350\267\257\351\200\232\350\256\257\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        label_73->setText(QApplication::translate("RunstateHelpPage", "B\350\267\257\351\200\232\350\256\257\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        labelSignalSystem_46->setText(QString());
        labelSignalSystem_47->setText(QString());
        labelSignalSystem_48->setText(QString());
        labelSignalSystem_49->setText(QString());
        labelSignalSystem_50->setText(QString());
        labelSignalSystem_51->setText(QString());
        labelSignalSystem_52->setText(QString());
        label_84->setText(QString());
        label_85->setText(QApplication::translate("RunstateHelpPage", "\347\211\265\345\274\225\345\205\201\350\256\270", 0, QApplication::UnicodeUTF8));
        labelSignalSystem_5->setText(QString());
        label_86->setText(QApplication::translate("RunstateHelpPage", "\351\200\232\350\256\257\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        labelSignalSystem_53->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class RunstateHelpPage: public Ui_RunstateHelpPage {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_RUNSTATEHELPPAGE_H
